CREATE TABLE IF NOT EXISTS boenden (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  namn text
);

CREATE TABLE IF NOT EXISTS rapporter (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  boende text NOT NULL,
  prio text NOT NULL CHECK (prio IN ('1', '2', '3')),
  atgard text NOT NULL,
  mapp_status text NOT NULL CHECK (mapp_status IN ('JA', 'NEJ')),
  brister text,
  fritext text
);

CREATE INDEX IF NOT EXISTS rapporter_created_at_idx ON rapporter (created_at DESC);
CREATE INDEX IF NOT EXISTS rapporter_boende_created_at_idx ON rapporter (boende, created_at DESC);

CREATE TABLE IF NOT EXISTS admin_login_throttles (
  client_key text PRIMARY KEY,
  window_started timestamptz NOT NULL,
  failures integer NOT NULL CHECK (failures >= 0),
  blocked_until timestamptz
);
